### ISSUE TITLE
iOS 6.x compability

### ISSUE THREAD

**Issue by mdornseif** [mochtu/libsodium-ios#1]
I see this is tagged

```
  s.ios.deployment_target = '7.0'
```

Is there a reason to make it only usable on Beta-iOS versions? Keeps me from distributing anything to non-iOS developers (for a few days only, but ...)

**Comment by mochtu** [comment]
Hi mdornseif,

yes, there is a reason. The headers and sources are precompiled with the XCode5 GM. This precompiler makes some decisions on what methods and systems to use later on. For security reasons and the fact that this is a crypto library I decided not to take any chances with older versions of XCode and iOS. 

Theoretically, and I didn't test that, it could also work if you compile with XCode5 and target iOS 6. I added a spec that allows iOS 6 to my Specs repo.

pod 'libsodium-ios', :podspec => 'https://raw.github.com/mochtu/Specs/master/libsodium-ios6-testing/0.4.3/libsodium-ios6-testing.podspec'

If you like you can test it and come back to me with the results. For beta-testing your app it should be fine. But I don't recommend that version for production apps.

Cheers,
Mo

**Comment by mdornseif** [comment]
Thanks!

Something like

```
platform :ios, '6.1'
pod 'libsodium-ios6-testing', :podspec => 'https://raw.github.com/mochtu/Specs/master/libsodium-ios6-testing/0.4.3/libsodium-ios6-testing.podspec'
```

now builds as expected. I'll come back if I see any strange behaviour.
