### ISSUE TITLE
Update for libsodium 0.5.0

### ISSUE THREAD

**Issue by gabriel** [mochtu/libsodium-ios#5]

**Comment by ghost** [comment]
I'm interested too

**Comment by tljones** [comment]
yes, please - would like to use new API crypto_box_easy() !

**Comment by gabriel** [comment]
I did some objc wrappers here:

https://github.com/gabriel/NAChloride/blob/master/NAChloride/NASecretBox.m

which does all the bytes padding stuff...

**Comment by ghost** [comment]
Thanks Gabriel,

I tried to use your wrapper but i need the crypto_hash and crypto_box/crypto_sign/etc so i finally i made my own wrapper. 
I'm having several problems with memory allocating and don't know if the 0.5 resolves these.

**Comment by gabriel** [comment]
Looks like libsodium works in 0.5.0 without edits.... I have a pull request for the spec there now https://github.com/CocoaPods/Specs/pull/12389

**Comment by gabriel** [comment]
ok just got the 0.5.0 podspec pushed
